# Copilot MCP (Model Context Protocol) configuration for live trading data access.

servers:
  - url: https://mboum-finance.p.rapidapi.com
    description: Yahoo Finance live market data via RapidAPI.
    token: ${{ secrets.RAPIDAPI_YAHOO_FINANCE_KEY }}
    headers:
      X-RapidAPI-Key: ${{ secrets.RAPIDAPI_YAHOO_FINANCE_KEY }}
      X-RapidAPI-Host: mboum-finance.p.rapidapi.com
  - url: https://www.alphavantage.co
    description: Alpha Vantage real-time trading data and analytics.
    token: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
  - url: https://api.marketstack.com
    description: MarketStack global market and exchange data.
    token: ${{ secrets.MARKETSTACK_API_KEY }}

notes:
  - These secrets are referenced from your GitHub repository settings.
  - You can add/remove providers as needed.
  - Never commit raw API keys in code.
