data:
  symbols:
    - AAPL
    - MSFT
    - GOOGL
    - AMZN
    - TSLA
    - NVDA
    - META
    - SPY
    - QQQ
  crypto_symbols:
    - BTC-USD
    - ETH-USD
    - SOL-USD
    - ADA-USD
  lookback_days: 252
  interval: 1d
  
  # Data sources configuration
  enabled_sources:
    - yahoo_finance
    - iex_cloud
    - alpha_vantage
    - finnhub
    - binance
  source_priority:
    - yahoo_finance
    - iex_cloud
    - alpha_vantage
    - finnhub
    - binance
    - quandl
  
  # Data pipeline settings
  enable_parallel_fetch: true
  enable_data_cleaning: true
  enable_data_enrichment: true
  enable_quality_assurance: true
  
  technical_indicators:
    - sma
    - ema
    - rsi
    - macd
    - bollinger
    - atr
    - stoch
    - williams
  candlestick_patterns:
    - doji
    - hammer
    - shooting_star
    - engulfing
    - harami
  
  # Enhanced feature engineering
  rolling_windows: [5, 10, 20, 50]
  volatility_windows: [10, 20, 50]
  enable_regime_detection: true
  enable_sentiment_features: true
  enable_meta_tags: true
  
  # Data cleaning settings
  outlier_detection_method: iqr
  missing_value_method: interpolate
  outlier_action: cap
  
  # Normalization settings
  normalization_method: minmax
  normalize_features: true
  
  # Bias reduction settings
  balance_criteria:
    max_per_sector: 5
    max_per_region: 10
    market_cap_distribution:
      Large Cap: 0.4
      Mid Cap: 0.3
      Small Cap: 0.2
      Micro Cap: 0.1
  
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15
  stratified_sampling: true

model:
  model_type: lstm
  sequence_length: 60
  hidden_size: 128
  num_layers: 3
  dropout: 0.2
  bidirectional: true
  d_model: 256
  n_heads: 8
  n_encoder_layers: 6
  dim_feedforward: 1024
  cnn_filters:
    - 64
    - 32
    - 16
  kernel_sizes:
    - 3
    - 3
    - 3
  dense_layers:
    - 64
    - 32
  output_size: 1
  activation: relu
  batch_norm: true
  layer_norm: false
  l1_reg: 0.0001
  l2_reg: 0.001

training:
  learning_rate: 0.001
  optimizer: adam
  weight_decay: 0.0001
  batch_size: 32
  epochs: 100
  early_stopping_patience: 10
  reduce_lr_patience: 5
  reduce_lr_factor: 0.5
  loss_function: mse
  loss_weights: null
  validation_freq: 1
  save_best_model: true
  gradient_clipping: 1.0
  mixed_precision: false
  accumulate_grad_batches: 1

risk:
  initial_capital: 100000.0
  max_position_size: 0.1
  max_portfolio_risk: 0.02
  stop_loss_pct: 0.05
  take_profit_pct: 0.15
  trailing_stop_pct: 0.03
  position_sizing_method: kelly
  volatility_lookback: 20
  max_drawdown_threshold: 0.1
  var_confidence: 0.05
  sharpe_min_threshold: 1.0

earnings:
  earnings_api_key: null
  earnings_lookback_quarters: 8
  earnings_features:
    - eps_surprise
    - revenue_surprise
    - eps_growth
    - revenue_growth
    - guidance_change
    - analyst_revisions
  pre_earnings_days: 5
  post_earnings_days: 3
  earnings_weight: 0.2

random_seed: 42
device: auto
data_dir: data
model_dir: models
logs_dir: logs
results_dir: results

# API keys for data sources (set these with your actual keys)
alpha_vantage_key: null
quandl_key: null
iex_cloud_key: null
iex_sandbox: true
finnhub_key: null
binance_api_key: null
binance_api_secret: null

# Data pipeline settings
enable_multi_source: true
save_pipeline_results: true
cache_data: true
parallel_processing: true