# GitHub Actions workflow for automated Modal deployment
# This workflow runs on every push to main branch and can be manually triggered
# 
# Prerequisites:
# 1. Add MODAL_TOKEN secret to repository settings
# 2. Ensure modal_app.py exists in the repository root
# 3. Ensure requirements.txt includes modal dependency
#
# Steps performed:
# 1. Check out the code from the repository
# 2. Set up Python 3.10 environment  
# 3. Install dependencies from requirements.txt
# 4. Configure Modal API token from secrets
# 5. Deploy the Modal application using modal_app.py

name: Deploy to Modal

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Set the Modal API token from the MODAL_TOKEN secret
      - name: Set Modal token
        run: |
          mkdir -p ~/.modal
          echo "${{ secrets.MODAL_TOKEN }}" > ~/.modal/token

      # Step 5: Deploy modal_app.py using 'modal deploy modal_app.py'
      - name: Deploy app to Modal
        run: modal deploy modal_app.py